# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: gradle:jdk16

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: gradle -v
      - run: gradle dependencies
      # run tests!
      - run: gradle test
      - run: gradle build
      - run:
          name: list
          command: |
            pwd
            ls -l

      - store_artifacts:
          path: build/libs/
      - store_test_results:
          path: build/test-results
      - run:
          name: Clone docs
          working_directory: ~/clonedir
          command: |
            git clone --depth 1 https://${DOCS_GITHUB_TOKEN}@github.com/f0rbit/gm-server.git -b javadocs
            pwd
            ls -a
      - deploy:
          name: Deploy docs
          working_directory: ~/clonedir/gm-server
          command: |
            pwd
            ls -a
            git config credential.helper 'cache --timeout=120'
            git config user.email "dev@forbit.dev"
            git config user.name "doc-bot"
            cp -a ~/repo/build/docs/javadoc/. ~/clonedir/gm-server/
            ls -l
            git add .
            git commit -m "Deployed docs via CircleCI"
            git push https://${DOCS_GITHUB_TOKEN}@github.com/f0rbit/gm-server.git javadocs
            echo "docs deployed"
